"""Add owner_id to Communication model

Revision ID: 1593af608f53
Revises: 
Create Date: 2025-03-20 10:52:44.635757

"""
from alembic import op
import sqlalchemy as sa
from alembic import context


# revision identifiers, used by Alembic.
revision = '1593af608f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_communications_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_churches_owner_id_users', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('churches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_churches_owner_id_users', type_='foreignkey')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_communications_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
