"""Add additional Church fields from old model

Revision ID: 811e9744caca
Revises: a85c9265937c
Create Date: 2025-03-21 15:48:08.324563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '811e9744caca'
down_revision = 'a85c9265937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # Using batch operations for SQLite compatibility
        with op.batch_alter_table('churches') as batch_op:
            batch_op.add_column(sa.Column('virtuous', sa.Boolean(), nullable=True, default=False))
            batch_op.add_column(sa.Column('senior_pastor_phone', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('senior_pastor_email', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('missions_pastor_first_name', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('missions_pastor_last_name', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('mission_pastor_phone', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('mission_pastor_email', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('primary_contact_first_name', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('primary_contact_last_name', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('primary_contact_phone', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('primary_contact_email', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('church_pipeline', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('priority', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('assigned_to', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('referred_by', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('info_given', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('reason_closed', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('year_founded', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('date_closed', sa.Date(), nullable=True))
        print("Successfully added new fields to churches table")
    except Exception as e:
        print(f"Error adding columns to churches table: {e}")
    
    # Skip other changes that could cause issues
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # Using batch operations for SQLite compatibility
        with op.batch_alter_table('churches') as batch_op:
            batch_op.drop_column('date_closed')
            batch_op.drop_column('year_founded')
            batch_op.drop_column('reason_closed')
            batch_op.drop_column('info_given')
            batch_op.drop_column('referred_by')
            batch_op.drop_column('source')
            batch_op.drop_column('assigned_to')
            batch_op.drop_column('priority')
            batch_op.drop_column('church_pipeline')
            batch_op.drop_column('primary_contact_email')
            batch_op.drop_column('primary_contact_phone')
            batch_op.drop_column('primary_contact_last_name')
            batch_op.drop_column('primary_contact_first_name')
            batch_op.drop_column('mission_pastor_email')
            batch_op.drop_column('mission_pastor_phone')
            batch_op.drop_column('missions_pastor_last_name')
            batch_op.drop_column('missions_pastor_first_name')
            batch_op.drop_column('senior_pastor_email')
            batch_op.drop_column('senior_pastor_phone')
            batch_op.drop_column('virtuous')
        print("Successfully removed fields from churches table")
    except Exception as e:
        print(f"Error removing columns from churches table: {e}")
    # ### end Alembic commands ###
