steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mobilize-crm:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mobilize-crm:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'mobilize-crm'
  - '--image'
  - 'gcr.io/$PROJECT_ID/mobilize-crm:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'DATABASE_URL=mobilize-db-url:latest,SECRET_KEY=mobilize-flask-secret:latest,GOOGLE_CLIENT_ID=mobilize-google-client-id:latest,GOOGLE_CLIENT_SECRET=mobilize-google-client-secret:latest'

# Tag with latest for easy reference
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/mobilize-crm:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/mobilize-crm:latest']

# Push the latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mobilize-crm:latest']

images:
- 'gcr.io/$PROJECT_ID/mobilize-crm:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/mobilize-crm:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s 