steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mobilize-app:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mobilize-app:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'mobilize-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/mobilize-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '10'
  - '--set-env-vars'
  - 'FLASK_ENV=production'
  - '--set-cloudsql-instances'
  - '$PROJECT_ID:us-central1:mobilize-db'

# Update latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/mobilize-app:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/mobilize-app:latest']

# Push latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mobilize-app:latest']

images:
- 'gcr.io/$PROJECT_ID/mobilize-app:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/mobilize-app:latest'

timeout: 1800s 