steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:$COMMIT_SHA', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'mobilize-crm'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'mobilize-crm-service-account@mobilize-crm.iam.gserviceaccount.com'
  - '--set-secrets'
  - 'DATABASE_URL=mobilize-db-url:latest,SECRET_KEY=mobilize-flask-secret:latest'
  - '--set-env-vars'
  - 'FLASK_APP=app.py,FLASK_ENV=production,LOG_LEVEL=INFO,LOG_TO_STDOUT=True,PREFERRED_URL_SCHEME=https,BASE_URL=https://mobilize-crm.org,SKIP_DB_INIT=True'

# Tag with latest for easy reference
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:$COMMIT_SHA', 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:latest']

# Push the latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:latest']

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:$COMMIT_SHA'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/mobilize-crm/mobilize-crm:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s 