"""Replace reminder booleans with reminder_option dropdown

Revision ID: 00a6f3565d53
Revises: ab1e0d1b31aa
Create Date: 2025-03-21 16:04:20.895006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '00a6f3565d53'
down_revision = 'ab1e0d1b31aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we'll focus only on removing the old reminder columns
    # The new columns already exist in the database
    
    # Drop the old reminder columns
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('reminder_1_day')
        batch_op.drop_column('reminder_2_hours')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we'll focus only on adding back the old reminder columns
    # The new columns will remain in the database
    
    with op.batch_alter_table('tasks') as batch_op:
        # Add back the removed columns
        batch_op.add_column(sa.Column('reminder_2_hours', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reminder_1_day', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.VARCHAR(), nullable=True))
    
    # ### end Alembic commands ###
