"""Add owner_id to Task model

Revision ID: 078ff034365a
Revises: 1593af608f53
Create Date: 2025-03-20 10:54:40.547457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078ff034365a'
down_revision = '1593af608f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_tasks_owner_id_users', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
