"""Add is_primary_contact to Person and remove primary contact fields from Church

Revision ID: 4cb401521a9e
Revises: 00a6f3565d53
Create Date: 2025-03-24 08:54:25.804568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4cb401521a9e'
down_revision = '00a6f3565d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: is_primary_contact column already exists in people table
    
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('action')
        batch_op.drop_column('details')
        batch_op.drop_column('next_sync_token')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('started_at')
    
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tasks_created_by', 'users', ['created_by'], ['id'])
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_created_by', type_='foreignkey')
    
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('next_sync_token', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('details', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    
    # Note: is_primary_contact column already existed before this migration
    # ### end Alembic commands ###
