"""Add image and preferred_contact_method to contacts table

Revision ID: 5be09d8bc98a
Revises: c6b19f008037
Create Date: 2025-03-21 15:34:20.083843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5be09d8bc98a'
down_revision = 'c6b19f008037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # Using batch operations for SQLite compatibility
        with op.batch_alter_table('contacts') as batch_op:
            batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))
        print("Successfully added new columns to contacts table")
    except Exception as e:
        print(f"Error adding columns to contacts table: {e}")
    
    # Skip other changes that could cause issues
    # op.alter_column('sync_history', 'status', existing_type=sa.VARCHAR(length=20), nullable=True)
    # op.drop_column('sync_history', 'updated_at')
    # op.drop_column('sync_history', 'action')
    # op.drop_column('sync_history', 'next_sync_token')
    # op.drop_column('sync_history', 'details')
    # op.drop_column('sync_history', 'started_at')
    # op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'])
    # op.alter_column('users', 'office_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # Using batch operations for SQLite compatibility
        with op.batch_alter_table('contacts') as batch_op:
            batch_op.drop_column('date_modified')
            batch_op.drop_column('date_created')
            batch_op.drop_column('preferred_contact_method')
            batch_op.drop_column('image')
        print("Successfully removed columns from contacts table")
    except Exception as e:
        print(f"Error removing columns from contacts table: {e}")
    
    # Skip other changes
    # op.alter_column('users', 'office_id', existing_type=sa.INTEGER(), nullable=False)
    # op.drop_constraint(None, 'tasks', type_='foreignkey')
    # op.add_column('sync_history', sa.Column('started_at', sa.DATETIME(), nullable=False))
    # op.add_column('sync_history', sa.Column('details', sqlite.JSON(), nullable=True))
    # op.add_column('sync_history', sa.Column('next_sync_token', sa.VARCHAR(length=255), nullable=True))
    # op.add_column('sync_history', sa.Column('action', sa.VARCHAR(length=50), nullable=False))
    # op.add_column('sync_history', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # op.alter_column('sync_history', 'status', existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
