"""Add missing fields to people table

Revision ID: add_missing_person_fields
Revises: 54265a913aab
Create Date: 2025-04-16 16:02:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_missing_person_fields'
down_revision = '54265a913aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # Using batch operations for SQLite compatibility
        with op.batch_alter_table('people', schema=None) as batch_op:
            batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('anniversary', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('employer', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('languages', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('facebook', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
            batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
            batch_op.add_column(sa.Column('last_contact', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('next_contact', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='active', nullable=True))
            batch_op.add_column(sa.Column('pipeline_status', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('pipeline_stage', sa.String(length=50), nullable=True))
            batch_op.add_column(sa.Column('priority', sa.String(length=50), server_default='MEDIUM', nullable=True))
            batch_op.add_column(sa.Column('assigned_to', sa.String(length=50), server_default='UNASSIGNED', nullable=True))
            batch_op.add_column(sa.Column('source', sa.String(length=50), server_default='UNKNOWN', nullable=True))
            batch_op.add_column(sa.Column('reason_closed', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('date_closed', sa.Date(), nullable=True))
            batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

        print("Successfully added new fields to people table")
    except Exception as e:
        print(f"Error adding columns to people table: {e}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('people', schema=None) as batch_op:
            batch_op.drop_column('tags')
            batch_op.drop_column('date_closed')
            batch_op.drop_column('reason_closed')
            batch_op.drop_column('source')
            batch_op.drop_column('assigned_to')
            batch_op.drop_column('priority')
            batch_op.drop_column('pipeline_stage')
            batch_op.drop_column('pipeline_status')
            batch_op.drop_column('status')
            batch_op.drop_column('next_contact')
            batch_op.drop_column('last_contact')
            batch_op.drop_column('website')
            batch_op.drop_column('instagram')
            batch_op.drop_column('linkedin')
            batch_op.drop_column('twitter')
            batch_op.drop_column('facebook')
            batch_op.drop_column('languages')
            batch_op.drop_column('skills')
            batch_op.drop_column('interests')
            batch_op.drop_column('employer')
            batch_op.drop_column('occupation')
            batch_op.drop_column('anniversary')
            batch_op.drop_column('birthday')
        print("Successfully removed fields from people table")
    except Exception as e:
        print(f"Error removing columns from people table: {e}")
    # ### end Alembic commands ### 